import React from "react";
import Head from "next/head";

import styles from "./cookies.module.scss";

import { info } from "@/info";
import MainLayout from "@/layouts/MainLayout";

const Terms = () => {
  return (
    <>
      <Head>
        <meta name="description" content={info.descr} />
        <title>Cookie Policy | Okiimdigital Ltd</title>
      </Head>

      <MainLayout darkBG>
        <section className={styles.CookieSection}>
          <div className="container">
            <div>
              <h1>Cookie Policy</h1>

              <div className={styles.CookieTextWrapper}>
                <h2>Definitions and key terms</h2>
                <p>
                  To help explain things as clearly as possible in this Cookie
                  Policy, every time any of these terms are referenced, are
                  strictly defined as:
                </p>

                <ul>
                  <li>
                    <strong>Cookie:</strong> small amount of data generated by a
                    website and saved by your web browser. It is used to
                    identify your browser, provide analytics, remember
                    information about you such as your language preference or
                    login information.
                  </li>
                  <li>
                    <strong>Company:</strong> when this policy mentions
                    “Company,” “we,” “us,” or “our,” it refers to{" "}
                    {info.fullname}, {info.address} that is responsible for your
                    information under this Cookie Policy.
                  </li>
                  <li>
                    <strong>Device:</strong> any internet connected device such
                    as a phone, tablet, computer or any other device that can be
                    used to visit {info.fullname} and use the services.
                  </li>
                  <li>
                    <strong>Personal Data:</strong> any information that
                    directly, indirectly, or in connection with other
                    information — including a personal identification number —
                    allows for the identification or identifiability of a
                    natural person.
                  </li>
                  <li>
                    <strong>Service:</strong> refers to the service provided by{" "}
                    {info.fullname} as described in the relative terms (if
                    available) and on this platform.
                  </li>
                  <li>
                    <strong>Third-party service:</strong> refers to advertisers,
                    contest sponsors, promotional and marketing partners, and
                    others who provide our content or whose products or services
                    we think may interest you.
                  </li>
                  <li>
                    <strong>Website:</strong> {info.fullname}&apos;s site, which
                    can be accessed via this URL:{" "}
                    <a href={`https://${info.url}/`}>https://{info.url}/.</a>
                  </li>
                  <li>
                    <strong>You:</strong> a person or entity that is registered
                    with {info.fullname} to use the Services.
                  </li>
                </ul>

                <h2>Introduction</h2>
                <p>
                  This Cookie Policy explains how {info.fullname} and its
                  affiliates (collectively &quot;{info.fullname}&quot;,
                  &quot;we&quot;, &quot;us&quot;, and &quot;ours&quot;), use
                  cookies and similar technologies to recognize you when you
                  visit our platform, including without limitation{" "}
                  <a href={`https://${info.url}/`}>https://{info.url}/</a> and
                  any related URLs, mobile or localized versions and related
                  domains / sub-domains (&quot;Websites&quot;). It explains what
                  these technologies are and why we use them, as well as the
                  choices for how to control them.
                </p>

                <h2>What is a cookie?</h2>
                <p>
                  A cookie is a small text file that is stored on your computer
                  or other internet connected device in order to identify your
                  browser, provide analytics, remember information about you
                  such as your language preference or login information.
                  They&apos;re completely safe and can&apos;t be used to run
                  programs or deliver viruses to your device.
                </p>

                <h2>Why do we use cookies?</h2>
                <p>
                  We use first party and/or third party cookies on our platform
                  for various purposes such as:
                </p>
                <ul>
                  <li>
                    To facilitate the operation and functionality of our
                    platform;
                  </li>
                  <li>
                    To improve your experience of our platform and make
                    navigating around them quicker and easier;
                  </li>
                  <li>
                    To allow us to make a bespoke user experience for you and
                    for us to understand what is useful or of interest to you;
                  </li>
                  <li>
                    To analyze how our platform is used and how best we can
                    customize it;
                  </li>
                  <li>
                    To identify future prospects and personalize marketing and
                    sales interactions with it;
                  </li>
                  <li>
                    To facilitate the tailoring of online advertising to your
                    interests.
                  </li>
                </ul>
                <h2>What type of cookies does {info.fullname} use?</h2>
                <p>
                  Cookies can either be session cookies or persistent cookies. A
                  session cookie expires automatically when you close your
                  browser. A persistent cookie will remain until it expires or
                  you delete your cookies. Expiration dates are set in the
                  cookies themselves; some may expire after a few minutes while
                  others may expire after multiple years. Cookies placed by the
                  website you&apos;re visiting are called “first party cookies”.
                </p>
                <p>
                  Strictly Necessary cookies are necessary for our platform to
                  function and cannot be switched off in our systems. They are
                  essential in order to enable you to navigate around the
                  platform and use its features. If you remove or disable these
                  cookies, we cannot guarantee that you will be able to use our
                  platform.
                </p>
              </div>
            </div>
          </div>
        </section>
      </MainLayout>
    </>
  );
};

export default Terms;
